### ISSUE TITLE
Egg does not install

### ISSUE THREAD

**Issue by redsnapper8t8** [mozilla-services/marteau#16]
setup.py refers to README.rst but README.rst is not pulled into the egg 

adding include README.rst to MANIFEST.in fixes the issue

**Comment by almet** [comment]
should be fixed, thanks.

**Comment by anentropic** [comment]
needs pushing up to pypi...? I still get that error when I `pip install marteau` today

**Comment by bpirte** [comment]
IOError: [Errno 2] No such file or directory: 'README.rst'
when install it on mac osx 10.8.4
